In [1]:
import numpy as np
import cv2



In [11]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
cap= cv2.VideoCapture(0)
   
#img = cv2.imread('Scan.jpg')

while True : 
    


    _,img=cap.read()
   # Covert the frame to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    
    faces=face_cascade.detectMultiScale(gray,1.3,4)
    print(faces)
 
    for (x, y, w, h) in faces:
        
        
        cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)

 # Display the updated frame as a video stream
    cv2.imshow('img', img)
 # Press the ESC key to exit the loop
    # 27 is the code for the ESC key
    k=cv2.waitKey(30) & 0xff
    if k==27:
        
        break 

cap.release()

# Destroy the window that was showing the video stream
cv2.destroyAllWindows()

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[244 200 233 233]]
[[235 191 240 240]]
[[239 168 229 229]]
[[241 162 230 230]]
[[243 182 233 233]]
[[245 184 233 233]]
[[248 178 232 232]]
[[250 183 234 234]]
[[258 188 230 230]]
[[257 181 234 234]]
[[262 184 230 230]]
[[267 190 234 234]]
[[267 188 238 238]]
[[270 193 232 232]]
[[268 189 238 238]]
[[273 185 238 238]]
[[275 187 233 233]]
[[274 190 234 234]]
[[274 190 234 234]]
[[273 184 241 241]]
[[275 188 237 237]]
[[277 188 234 234]]
[[278 185 233 233]]
[[270 178 249 249]]
[[266 172 261 261]]
[[277 177 245 245]]
[[281 174 243 243]]
[[279 173 249 249]]
[[277 168 258 258]]
[[271 165 263 263]]
[[272 163 257 257]]
[[276 168 252 252]]
[[267 162 261 261]]
[[271 164 256 256]]
[[271 168 257 257]]
[[275 169 250 250]]
[[270 169 261 261]]
[[281 171 252 252]]
[[286 181 244 244]]
[[280 179 253 253]]
[[279 179 258 258]]
[[281 180 257 257]]
[[287 186 248

In [10]:
'''
When object detection models are trained, they are trained to detect faces of a certain size and might miss faces 
that are bigger or smaller than they expect. With this in mind, the image is resized several times in the hopes 
that a face will end up being a "detectable" size. The scaleFactor lets OpenCV know how much to scale the images. 
In our case, 1.3 means that it can scale 30% down to try and match the faces better.


As for the minNeighbors parameter, it's used to control the number of false positives and false negatives.
It defines the minimum number of positive rectangles (detect facial features) that need to be adjacent
to a positive rectangle in order for it to be considered actually positive. If minNeighbors is set to 0, 
the slightest hint of a face
will be counted as a definitive face, even if no other facial features are detected near it.

'''

'\nWhen object detection models are trained, they are trained to detect faces of a certain size and might miss faces \nthat are bigger or smaller than they expect. With this in mind, the image is resized several times in the hopes \nthat a face will end up being a "detectable" size. The scaleFactor lets OpenCV know how much to scale the images. \nIn our case, 1.3 means that it can scale 30% down to try and match the faces better.\n\n\nAs for the minNeighbors parameter, it\'s used to control the number of false positives and false negatives.\nIt defines the minimum number of positive rectangles (detect facial features) that need to be adjacent\nto a positive rectangle in order for it to be considered actually positive. If minNeighbors is set to 0, \nthe slightest hint of a face\nwill be counted as a definitive face, even if no other facial features are detected near it.\n\n'